spring.application.name=eco_backend

app.library.path=${APP_LIBRARY_PATH:./music/library/}
app.raw.path=${APP_RAW_PATH:./music/raw/}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/eco}
spring.datasource.username=${DB_USER:eco}
spring.datasource.password=${DB_PASS:eco}

spring.datasource.driver-class-name=${DB_TYPE:org.postgresql.Driver}
spring.jpa.hibernate.ddl-auto=update